# Generated by Django 3.0.2 on 2020-06-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0005_team_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='deadline',
            field=models.DateField(default='2020-06-14', help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
            preserve_default=False,
        ),
    ]
