# Generated by Django 3.0.2 on 2020-06-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0006_events_deadline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partners',
        ),
    ]
